// dev_cms_admin/src/views/console/statistics.vue
<script setup lang="ts">
import { ref, onMounted } from 'vue'
import { useApiAdmin, type StatisticsData } from '@/composables/useApiAdmin'

const api = useApiAdmin()
const statistics = ref<StatisticsData | null>(null)
const loading = ref(false)
const error = ref<string | null>(null)

/**
 * 格式化文件大小
 */
function formatFileSize(bytes: number): string {
    if (bytes === 0) return '0 B'
    const k = 1024
    const sizes = ['B', 'KB', 'MB', 'GB', 'TB']
    const i = Math.floor(Math.log(bytes) / Math.log(k))
    return `${(bytes / Math.pow(k, i)).toFixed(2)} ${sizes[i]}`
}

/**
 * 格式化数字
 */
function formatNumber(num: number): string {
    if (num >= 1000000) {
        return `${(num / 1000000).toFixed(1)}M`
    }
    if (num >= 1000) {
        return `${(num / 1000).toFixed(1)}K`
    }
    return num.toString()
}

/**
 * 加载统计数据
 */
async function loadStatistics() {
    loading.value = true
    error.value = null
    try {
        const res = await api.getStatistics()
        if (res.code === 200 && res.data) {
            statistics.value = res.data
        } else {
            error.value = res.message || '获取统计数据失败'
        }
    } catch (err) {
        error.value = err instanceof Error ? err.message : '网络请求失败'
    } finally {
        loading.value = false
    }
}

onMounted(() => {
    loadStatistics()
})

// 统计卡片配置
const statCards = [
    {
        key: 'posts',
        label: '文章总数',
        icon: 'i-lucide-file-text',
        color: 'blue',
        value: () => statistics.value?.posts ?? 0,
    },
    {
        key: 'published_posts',
        label: '已发布',
        icon: 'i-lucide-check-circle',
        color: 'green',
        value: () => statistics.value?.published_posts ?? 0,
    },
    {
        key: 'draft_posts',
        label: '草稿',
        icon: 'i-lucide-edit',
        color: 'yellow',
        value: () => statistics.value?.draft_posts ?? 0,
    },
    {
        key: 'comments',
        label: '评论总数',
        icon: 'i-lucide-message-square',
        color: 'purple',
        value: () => statistics.value?.comments ?? 0,
    },
    {
        key: 'approved_comments',
        label: '已通过',
        icon: 'i-lucide-check',
        color: 'green',
        value: () => statistics.value?.approved_comments ?? 0,
    },
    {
        key: 'pending_comments',
        label: '待审核',
        icon: 'i-lucide-clock',
        color: 'orange',
        value: () => statistics.value?.pending_comments ?? 0,
    },
    {
        key: 'attachments',
        label: '附件总数',
        icon: 'i-lucide-paperclip',
        color: 'indigo',
        value: () => statistics.value?.attachments ?? 0,
    },
    {
        key: 'attachments_size',
        label: '附件总大小',
        icon: 'i-lucide-hard-drive',
        color: 'teal',
        value: () => statistics.value?.attachments_size ?? 0,
        format: (val: number) => formatFileSize(val),
    },
    {
        key: 'categories',
        label: '分类',
        icon: 'i-lucide-folder',
        color: 'pink',
        value: () => statistics.value?.categories ?? 0,
    },
    {
        key: 'tags',
        label: '标签',
        icon: 'i-lucide-tag',
        color: 'cyan',
        value: () => statistics.value?.tags ?? 0,
    },
    {
        key: 'users',
        label: '用户总数',
        icon: 'i-lucide-users',
        color: 'gray',
        value: () => statistics.value?.users ?? 0,
    },
    {
        key: 'total_views',
        label: '总浏览量',
        icon: 'i-lucide-eye',
        color: 'red',
        value: () => statistics.value?.total_views ?? 0,
        format: (val: number) => formatNumber(val),
    },
]

function refreshStatistics() {
    loadStatistics()
}
</script>

<template>
    <UPageHeader
        title="数据统计"
        description="管理站点数据统计"
        :links="[{ label: '刷新', icon: 'i-lucide-refresh-cw', onClick: refreshStatistics }]"
    />
    <div class="space-y-6">
        <div v-if="error"
            class="rounded-lg border border-red-200 bg-red-50 p-4 text-red-800 dark:border-red-800 dark:bg-red-900/20 dark:text-red-400">
            <div class="flex items-center gap-2">
                <UIcon name="i-lucide-alert-circle" class="h-5 w-5" />
                <span>{{ error }}</span>
            </div>
        </div>

        <div v-else class="grid grid-cols-1 gap-4 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">
            <UCard v-for="card in statCards" :key="card.key" class="transition-shadow hover:shadow-lg">
                <div class="flex items-center justify-between">
                    <div class="flex-1">
                        <p class="text-sm font-medium text-gray-600 dark:text-gray-400">{{ card.label }}</p>
                        <p class="mt-2 text-2xl font-bold">
                            <template v-if="loading && !statistics">
                                <span
                                    class="inline-block h-8 w-16 animate-pulse rounded bg-gray-200 dark:bg-gray-700"></span>
                            </template>
                            <template v-else>
                                {{ card.format ? card.format(card.value()) : formatNumber(card.value()) }}
                            </template>
                        </p>
                    </div>
                    <div class="flex h-12 w-12 items-center justify-center rounded-lg" :class="{
                        'bg-blue-100 dark:bg-blue-900/20': card.color === 'blue',
                        'bg-green-100 dark:bg-green-900/20': card.color === 'green',
                        'bg-yellow-100 dark:bg-yellow-900/20': card.color === 'yellow',
                        'bg-purple-100 dark:bg-purple-900/20': card.color === 'purple',
                        'bg-orange-100 dark:bg-orange-900/20': card.color === 'orange',
                        'bg-indigo-100 dark:bg-indigo-900/20': card.color === 'indigo',
                        'bg-teal-100 dark:bg-teal-900/20': card.color === 'teal',
                        'bg-pink-100 dark:bg-pink-900/20': card.color === 'pink',
                        'bg-cyan-100 dark:bg-cyan-900/20': card.color === 'cyan',
                        'bg-gray-100 dark:bg-gray-900/20': card.color === 'gray',
                        'bg-red-100 dark:bg-red-900/20': card.color === 'red',
                    }">
                        <UIcon :name="card.icon" class="h-6 w-6" :class="{
                            'text-blue-600 dark:text-blue-400': card.color === 'blue',
                            'text-green-600 dark:text-green-400': card.color === 'green',
                            'text-yellow-600 dark:text-yellow-400': card.color === 'yellow',
                            'text-purple-600 dark:text-purple-400': card.color === 'purple',
                            'text-orange-600 dark:text-orange-400': card.color === 'orange',
                            'text-indigo-600 dark:text-indigo-400': card.color === 'indigo',
                            'text-teal-600 dark:text-teal-400': card.color === 'teal',
                            'text-pink-600 dark:text-pink-400': card.color === 'pink',
                            'text-cyan-600 dark:text-cyan-400': card.color === 'cyan',
                            'text-gray-600 dark:text-gray-400': card.color === 'gray',
                            'text-red-600 dark:text-red-400': card.color === 'red',
                        }" />
                    </div>
                </div>
            </UCard>
        </div>
    </div>
</template>

// dev_cms_admin/src/pages/Statistics.tsx
import { useEffect, useState, useRef } from 'react'
import { Card, Row, Col, Statistic, Spin, message } from 'antd'
import {
  FileTextOutlined,
  CommentOutlined,
  FileOutlined,
  FolderOutlined,
  TagOutlined,
  UserOutlined,
  EyeOutlined,
  CheckCircleOutlined,
  ClockCircleOutlined,
} from '@ant-design/icons'
import { useApiAdmin } from '@/hooks'
import { AdminApi, type StatisticsData } from '@/services/admin'

function formatFileSize(bytes: number): string {
  if (bytes === 0) return '0 B'
  const k = 1024
  const sizes = ['B', 'KB', 'MB', 'GB', 'TB']
  const i = Math.floor(Math.log(bytes) / Math.log(k))
  return Math.round((bytes / Math.pow(k, i)) * 100) / 100 + ' ' + sizes[i]
}

export default function Statistics() {
  const apiAdmin = useApiAdmin()
  const [loading, setLoading] = useState(true)
  const [data, setData] = useState<StatisticsData | null>(null)
  const fetchingRef = useRef(false)

  useEffect(() => {
    if (fetchingRef.current) return

    const fetchData = async () => {
      fetchingRef.current = true
      try {
        setLoading(true)
        const res = await AdminApi.getStatistics(apiAdmin)
        if (res.data) {
          setData(res.data)
        }
      } catch (err) {
        message.error('获取统计数据失败')
        console.error(err)
      } finally {
        setLoading(false)
        fetchingRef.current = false
      }
    }

    fetchData()
  }, [])

  if (loading) {
    return (
      <div style={{ textAlign: 'center', padding: '50px' }}>
        <Spin size="large" />
      </div>
    )
  }

  return (
    <div>
      <Row gutter={[16, 16]}>
        <Col xs={24} sm={12} lg={6}>
          <Card>
            <Statistic
              title="文章总数"
              value={data?.posts || 0}
              prefix={<FileTextOutlined />}
            />
          </Card>
        </Col>
        <Col xs={24} sm={12} lg={6}>
          <Card>
            <Statistic
              title="已发布"
              value={data?.published_posts || 0}
              prefix={<CheckCircleOutlined />}
              valueStyle={{ color: '#3f8600' }}
            />
          </Card>
        </Col>
        <Col xs={24} sm={12} lg={6}>
          <Card>
            <Statistic
              title="草稿"
              value={data?.draft_posts || 0}
              prefix={<ClockCircleOutlined />}
              valueStyle={{ color: '#cf1322' }}
            />
          </Card>
        </Col>
        <Col xs={24} sm={12} lg={6}>
          <Card>
            <Statistic
              title="总访问量"
              value={data?.total_views || 0}
              prefix={<EyeOutlined />}
            />
          </Card>
        </Col>
        <Col xs={24} sm={12} lg={6}>
          <Card>
            <Statistic
              title="评论总数"
              value={data?.comments || 0}
              prefix={<CommentOutlined />}
            />
          </Card>
        </Col>
        <Col xs={24} sm={12} lg={6}>
          <Card>
            <Statistic
              title="待审核"
              value={data?.pending_comments || 0}
              prefix={<ClockCircleOutlined />}
              valueStyle={{ color: '#faad14' }}
            />
          </Card>
        </Col>
        <Col xs={24} sm={12} lg={6}>
          <Card>
            <Statistic
              title="已通过"
              value={data?.approved_comments || 0}
              prefix={<CheckCircleOutlined />}
              valueStyle={{ color: '#3f8600' }}
            />
          </Card>
        </Col>
        <Col xs={24} sm={12} lg={6}>
          <Card>
            <Statistic
              title="用户总数"
              value={data?.users || 0}
              prefix={<UserOutlined />}
            />
          </Card>
        </Col>
        <Col xs={24} sm={12} lg={6}>
          <Card>
            <Statistic
              title="分类数"
              value={data?.categories || 0}
              prefix={<FolderOutlined />}
            />
          </Card>
        </Col>
        <Col xs={24} sm={12} lg={6}>
          <Card>
            <Statistic
              title="标签数"
              value={data?.tags || 0}
              prefix={<TagOutlined />}
            />
          </Card>
        </Col>
        <Col xs={24} sm={12} lg={6}>
          <Card>
            <Statistic
              title="附件数"
              value={data?.attachments || 0}
              prefix={<FileOutlined />}
            />
          </Card>
        </Col>
        <Col xs={24} sm={12} lg={6}>
          <Card>
            <Statistic
              title="附件总大小"
              value={formatFileSize(data?.attachments_size || 0)}
              prefix={<FileOutlined />}
            />
          </Card>
        </Col>
      </Row>
    </div>
  )
}
